# Generated by Django 4.0.3 on 2022-03-17 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0005_profile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
    ]
