# Generated by Django 4.0.3 on 2022-03-17 09:23

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0007_alter_banuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_accounts.profile'),
        ),
    ]
