# Generated by Django 4.0.3 on 2022-03-17 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0009_alter_banuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
