# Generated by Django 4.0.3 on 2022-03-18 14:50

import Journal.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0010_alter_banuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[Journal.validators.validators.name_only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=25, validators=[Journal.validators.validators.name_only_letters_validator]),
        ),
    ]
