# Generated by Django 4.0.3 on 2022-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
