# Generated by Django 4.0.3 on 2022-03-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_remove_profile_user_delete_appuser_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
