# Generated by Django 4.0.3 on 2022-03-24 09:06

import Journal.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_journal_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20, validators=[Journal.validators.validators.min_length_validator])),
                ('message', models.TextField()),
            ],
        ),
    ]
