# Generated by Django 4.0.3 on 2022-04-04 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
