# Generated by Django 4.0.3 on 2022-04-04 08:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_journal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
