# Generated by Django 4.0.3 on 2022-03-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_posts', '0006_post_feeling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create']},
        ),
    ]
