# Generated by Django 4.0.3 on 2022-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_posts', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
