# Generated by Django 4.0.3 on 2022-03-21 16:48

import Journal.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_posts', '0010_post_body_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, validators=[Journal.validators.validators.min_length_validator]),
        ),
    ]
